server {
  server_name ws.agarvvv.seo4starters.net;
  access_log /var/log/nginx/agarvvv-seo4starters-ws-access.log agarvvv_diag;
  error_log /var/log/nginx/agarvvv-seo4starters-ws-error.log warn;
  return 301 https://agarvvv.greener-business.com$request_uri;

  listen [::]:443 ssl;
  listen 443 ssl;
  ssl_certificate /etc/letsencrypt/live/ws.agarvvv.seo4starters.net/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/ws.agarvvv.seo4starters.net/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
  listen 80;
  listen [::]:80;
  server_name ws.agarvvv.seo4starters.net;

  return 301 https://agarvvv.greener-business.com$request_uri;
}
